// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	common "tsc_demo/backend/common"

	mock "github.com/stretchr/testify/mock"
)

// RawHistoryGetter is an autogenerated mock type for the RawHistoryGetter type
type RawHistoryGetter struct {
	mock.Mock
}

// GetBrowserHistory provides a mock function with given fields:
func (_m *RawHistoryGetter) GetBrowserHistory() ([]common.BrowserHistoryRecord, error) {
	ret := _m.Called()

	var r0 []common.BrowserHistoryRecord
	if rf, ok := ret.Get(0).(func() []common.BrowserHistoryRecord); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.BrowserHistoryRecord)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
